version: '3.8'
services:
  db:
    container_name: database
    platform: linux/amd64
    image: mysql:8.0
    ports:
        - "3306:3306"
    command: 
        - '--character-set-server=utf8mb4'
        - '--collation-server=utf8mb4_general_ci'
    volumes:
        - .db:/var/lib/mysql
        - ./templateSql.sql:/docker-entrypoint-initdb.d/templateSql.sql:root
    environment:
      MYSQL_DATABASE: "cme_quest_adventures"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: "%"
  php:
    container_name: webview
    depends_on:
      - db
    image: cmequest:v1
    ports:
      - "8000:80"
    stdin_open: true
    volumes:
      - ./webserver:/var/www/html
    build:
        dockerfile: Dockerfile
  # godot:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile  # Path to your Dockerfile containing Godot setup
  #   volumes:
  #     - .:/usr/src/app/project  # Mount the local Godot project
  #   command: ["godot", "--path", "/usr/src/app/project", "--no-window"]  # Run Godot with the specific project
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]